name: Test cron job

on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test cron job
        run: echo "Cron job called"
